name: Publish Docker

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.release.tag_name }
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesatjaminit/jam-bot:latest
      - name: Build and push tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesatjaminit/jam-bot:${{ env.IMAGE_TAG }}
