name: Publish Dev Docker Jam-Bot

on:
  push:
    branches: [main]
    paths:
      - "packages/jam-bot/**"
      - "!packages/jam-bot/**/devScripts/**"
      - "!packages/jam-bot/.env.example"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/jam-bot
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesatjaminit/jam-bot:dev
