name: Publish Dev Docker Jam-Bot

on:
  push:
    branches: [main]
    paths:
      - "packages/jam-bot/**"
      - "!packages/jam-bot/**/devScripts/**"
      - "!packages/jam-bot/.env.example"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesatjaminit/jam-bot:dev
          context: ./packages/jam-bot/
