name: Release Docker Jam-Bot

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push version
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesatjaminit/jam-bot:${{ github.event.inputs.version }}
      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesatjaminit/jam-bot:latest
